spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:file:./test;AUTO_SERVER=TRUE;
    username: sa
    password:
    driver-class-name: org.h2.Driver