spring:
  datasource:
    url: ${RDS_DB_URL}
    username: ${RDS_DB_USERNAME}
    password: ${RDS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect