pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Clone Repository'
                echo 'Branch : develop'
                git branch: 'develop', url: 'https://lab.ssafy.com/s09-bigdata-dist-sub2/S09P22A602', credentialsId: 'gitlab_dmz_jyj2487'
            }
        }

        stage('Set Environment') {
            steps {
                echo 'Copy require file to pipeline folder'
				sh 'cp /var/jenkins_home/util/env.yml ./server/src/main/resources/env.yml'
            }
        }
    
        stage('Docker down') {
            steps {
                echo 'Docker compose down'
                sh 'sudo docker-compose down --rmi all'
            }
        }
    
        stage('Docker Build') {
            steps {
                echo 'docker compose build'
				sh 'sudo docker-compose build --no-cache'
            }
			post {
				success {
					echo 'Success to build'
				}
				failure {
					echo 'Docker build failed. clear unused file'
					sh 'sudo docker system prune -f'
					error 'pipeline aborted'
				}
			}
        }
        
        stage('Docker up') {
            steps {
                echo 'Docker compose up'
                sh 'sudo docker-compose up -d'
            }
        }  
        
        stage('Docker clear') {
            steps {
                sh 'docker system prune -f'
            }
        }    
    }
    post {
        success {
        	script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (color: 'good', 
                message: "배포 성공: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)", 
                endpoint: 'https://meeting.ssafy.com/hooks/96q8w8rgnjn19k4bndtcuxfhko', 
                channel: 'A602_bot'
                )
            }
        }
        failure {
        	script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (color: 'danger', 
                message: "배포 실패: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)", 
                endpoint: 'https://meeting.ssafy.com/hooks/96q8w8rgnjn19k4bndtcuxfhko', 
                channel: 'A602_bot'
                )
            }
        }
    }
}