version: '3.2'

services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
      args:
        ELK_VERSION: ${ELK_VERSION}
    volumes:
      - type: bind
        source: './elasticsearch/config/elasticsearch.yml'
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: './elasticsearch/data'
        target: /usr/share/elasticsearch/data
    ports:
      - '3200:9200'
      - '3300:9300'
    environment:
      ES_JAVA_OPTS: '-Xmx256m -Xms256m'
      ELASTIC_PASSWORD: ${ELK_PASSWORD}
      discovery.type: single-node
    networks:
      - elk

  logstash:
    container_name: logstash
    build:
      context: ./logstash
      dockerfile: Dockerfile
      args:
        ELK_VERSION: ${ELK_VERSION}
    volumes:
      - type: bind
        source: './logstash/config/logstash.yml'
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: './logstash/pipeline'
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - '40000:5001/tcp'
      - '40000:5001/udp'
      - '3600:9600'
    environment:
      LS_JAVA_OPTS: '-Xmx256m -Xms256m'
      LOGSTASH_INTERNAL_PASSWORD: ${ELK_PASSWORD}
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    build:
      context: ./kibana
      dockerfile: Dockerfile
      args:
        ELK_VERSION: ${ELK_VERSION}
    volumes:
      - type: bind
        source: './kibana/config/kibana.yml'
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - '3601:5601'
    environment:
      KIBANA_SYSTEM_PASSWORD: ${ELK_PASSWORD}
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
